server:
  port: 8085
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto-ecommerce
    username: postgres
    password: senha